# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'action/avatars'),
        ),
    ]
