# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170105_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendid', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friends',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
        migrations.AddField(
            model_name='notification',
            name='Invitationid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='actionlikedid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='calendaractionid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='friend_like_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='privateGroupid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationtype',
            field=models.CharField(choices=[(b'L', b'Liked'), (b'C', b'Commented'), (b'I', b'Invitation'), (b'A', b'Accepted'), (b'D', b'Deadlined'), (b'F', b'ClosedAction'), (b'R', b'ReplyComment')], max_length=1),
        ),
    ]
